name: Terraform Pipeline

on:
  push:
    branches:
    - main

env:
  TERRAFORM_VERSION: 1.12.2

jobs:

  tf-aws:
    name: AWS provider
    runs-on: ubuntu-latest
 
    steps:

    - name: Step 01 - Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION

    - name: Step 02 - CheckOut GitHub Repo
      uses: actions/checkout@v4

    - name: Step 03 - Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token    : ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region           : us-east-1

    - name: Step 04 - Terraform Init
      run : terraform -chdir=./terraform init

    - name: Step 05 - Terraform Validate
      run : terraform -chdir=./terraform validate

    - name: Step 06 - Terraform Plan
      run : terraform -chdir=./terraform plan -out tfplan

    - name: Step 07 - Terraform Apply
      run : terraform -chdir=./terraform apply tfplan

    - name: Step 08 - Terraform Show
      run : terraform -chdir=./terraform show